Repository vukasinmilosevic/Fiducial_XS, pull requests merged in 2022-03, with the labels that each got.

#6 Adding ReadTheDocs template + switching to .rst write-up
  .gitignore
  README.md
  README.rst
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/make.bat
Labels: documentation

#9 Fixed plotter
  python/createXSworkspace.py
  python/plotAsimov_simultaneous.py
  python/plotDifferentialBins.py
  python/plotLHScans.py
  runHZZFiducialXS.py
Labels: bugfix

#8 Fix for the multi-bin datacards
  python/createXSworkspace.py
  python/datacard_maker.py
  python/plotAsimov_simultaneous.py
  python/plotDifferentialBins.py
  python/plotLHScans.py
  runHZZFiducialXS.py
Labels: enhancement, bugfix

#11 General updates related to RooFit warning, Restructuring workspaces path, etc.
  Inputs/Input_Info.py
  Inputs/observables_list.yml
  README.rst
  RunEverything.py
  efficiencyFactors.py
  getUnc_Unc.py
  python/LoadData.py
  python/Utils.py
  python/__init__.py
  python/addConstrainedModel.py
  python/collectInputs.py
  python/createXSworkspace.py
  python/obsList.py
  python/plot2dsigeffs.py
  python/plotAsimov_inclusive.py
  python/plotAsimov_simultaneous.py
  python/plotDifferentialBins.py
  python/plotLHScans.py
  python/producePlots.py
  runHZZFiducialXS.py
  scripts/doLScan_mass4l.sh
  setup.sh
  templates/fiducialXSTemplates.C
  xs_125.0_1bin/hzz4l_2e2muS_13TeV_xs_inclusive_bin0.txt
  xs_125.0_1bin/hzz4l_4eS_13TeV_xs_inclusive_bin0.txt
  xs_125.0_1bin/hzz4l_4muS_13TeV_xs_inclusive_bin0.txt
Labels: enhancement, Formatting

#19 Adding initial implementation of the double differential measurement for the efficiency module
  Inputs/observables_list.yml
  efficiencyFactors.py
  getUnc_Unc.py
  python/Utils.py
  python/collectInputs.py
  python/plotDifferentialBins.py
  python/read_bins.py
Labels: documentation, enhancement, Formatting

#23 interpolation module
  README.rst
  RunEverything.py
  python/LoadData.py
  python/Utils.py
  python/collectInputs.py
  python/interpolate_differential_full.py
  python/interpolate_differential_pred.py
  python/sample_shortnames.py
Labels: enhancement
