Repository vukasinmilosevic/Fiducial_XS, pull requests merged in 2022-07, with the labels that each got.

#57 Adding the datacard inputs for JES related variables
  Inputs/JES/2016/TauB_Inc_0j_pTWgt/inputs_JESnuis_TauB_Inc_0j_pTWgt.py
  Inputs/JES/2016/TauC_Inc_0j_EnergyWgt/inputs_JESnuis_TauC_Inc_0j_EnergyWgt.py
  Inputs/JES/2016/TauC_Inc_0j_EnergyWgt_vs_pT4l/inputs_JESnuis_TauC_Inc_0j_EnergyWgt_vs_pT4l.py
  Inputs/JES/2016/dEtaj1j2/inputs_JESnuis_dEtaj1j2.py
  Inputs/JES/2016/dPhij1j2/inputs_JESnuis_dPhij1j2.py
  Inputs/JES/2016/mass4l/inputs_yields_mass4l.py
  Inputs/JES/2016/mass4lj/inputs_JESnuis_mass4lj.py
  Inputs/JES/2016/mj1j2/inputs_JESnuis_mj1j2.py
  Inputs/JES/2016/njets_pt30_eta2p5/inputs_JESnuis_njets_pt30_eta2p5.py
  Inputs/JES/2016/njets_pt30_eta4p7/inputs_JESnuis_njets_pt30_eta4p7.py
  Inputs/JES/2016/njets_pt30_eta4p7_vs_pT4l/inputs_JESnuis_njets_pt30_eta4p7_vs_pT4l.py
  Inputs/JES/2016/pT4l_vs_pT4lj/inputs_JESnuis_pT4l_vs_pT4lj.py
  Inputs/JES/2016/pT4lj/inputs_JESnuis_pT4lj.py
  Inputs/JES/2016/pT4ljj/inputs_JESnuis_pT4ljj.py
  Inputs/JES/2016/pTj2/inputs_JESnuis_pTj2.py
  Inputs/JES/2016/pt_leadingjet_pt30_eta4p7/inputs_JESnuis_pt_leadingjet_pt30_eta4p7.py
  Inputs/JES/2016/pt_leadingjet_pt30_eta4p7_vs_pTj2/inputs_JESnuis_pt_leadingjet_pt30_eta4p7_vs_pTj2.py
  Inputs/JES/2017/TauB_Inc_0j_pTWgt/inputs_JESnuis_TauB_Inc_0j_pTWgt.py
  Inputs/JES/2017/TauC_Inc_0j_EnergyWgt/inputs_JESnuis_TauC_Inc_0j_EnergyWgt.py
  Inputs/JES/2017/TauC_Inc_0j_EnergyWgt_vs_pT4l/inputs_JESnuis_TauC_Inc_0j_EnergyWgt_vs_pT4l.py
  Inputs/JES/2017/dEtaj1j2/inputs_JESnuis_dEtaj1j2.py
  Inputs/JES/2017/dPhij1j2/inputs_JESnuis_dPhij1j2.py
  Inputs/JES/2017/mass4l/inputs_yields_mass4l.py
  Inputs/JES/2017/mass4lj/inputs_JESnuis_mass4lj.py
  Inputs/JES/2017/mj1j2/inputs_JESnuis_mj1j2.py
  Inputs/JES/2017/njets_pt30_eta2p5/inputs_JESnuis_njets_pt30_eta2p5.py
  Inputs/JES/2017/njets_pt30_eta4p7/inputs_JESnuis_njets_pt30_eta4p7.py
  Inputs/JES/2017/njets_pt30_eta4p7/inputs_JESnuis_njets_pt30_eta4p7_vs_pT4l.py
  Inputs/JES/2017/njets_pt30_eta4p7_vs_pT4l/inputs_JESnuis_njets_pt30_eta4p7_vs_pT4l.py
  Inputs/JES/2017/pT4l_vs_pT4lj/inputs_JESnuis_pT4l_vs_pT4lj.py
  Inputs/JES/2017/pT4lj/inputs_JESnuis_pT4lj.py
  Inputs/JES/2017/pT4ljj/inputs_JESnuis_pT4ljj.py
  Inputs/JES/2017/pTj2/inputs_JESnuis_pTj2.py
  Inputs/JES/2017/pt_leadingjet_pt30_eta4p7/inputs_JESnuis_pt_leadingjet_pt30_eta4p7.py
  Inputs/JES/2017/pt_leadingjet_pt30_eta4p7_vs_pTj2/inputs_JESnuis_pt_leadingjet_pt30_eta4p7_vs_pTj2.py
  Inputs/JES/2018/TauB_Inc_0j_pTWgt/inputs_JESnuis_TauB_Inc_0j_pTWgt.py
  Inputs/JES/2018/TauC_Inc_0j_EnergyWgt/inputs_JESnuis_TauC_Inc_0j_EnergyWgt.py
  Inputs/JES/2018/TauC_Inc_0j_EnergyWgt_vs_pT4l/inputs_JESnuis_TauC_Inc_0j_EnergyWgt_vs_pT4l.py
  Inputs/JES/2018/dEtaj1j2/inputs_JESnuis_dEtaj1j2.py
  Inputs/JES/2018/dPhij1j2/inputs_JESnuis_dPhij1j2.py
  Inputs/JES/2018/mass4l/inputs_yields_mass4l.py
  Inputs/JES/2018/mass4lj/inputs_JESnuis_mass4lj.py
  Inputs/JES/2018/mj1j2/inputs_JESnuis_mj1j2.py
  Inputs/JES/2018/njets_pt30_eta2p5/inputs_JESnuis_njets_pt30_eta2p5.py
  Inputs/JES/2018/njets_pt30_eta4p7/inputs_JESnuis_njets_pt30_eta4p7.py
  Inputs/JES/2018/njets_pt30_eta4p7_vs_pT4l/inputs_JESnuis_njets_pt30_eta4p7_vs_pT4l.py
  Inputs/JES/2018/pT4l_vs_pT4lj/inputs_JESnuis_pT4l_vs_pT4lj.py
  Inputs/JES/2018/pT4lj/inputs_JESnuis_pT4lj.py
  Inputs/JES/2018/pT4ljj/inputs_JESnuis_pT4ljj.py
  Inputs/JES/2018/pTj2/inputs_JESnuis_pTj2.py
  Inputs/JES/2018/pt_leadingjet_pt30_eta4p7/inputs_JESnuis_pt_leadingjet_pt30_eta4p7.py
  Inputs/JES/2018/pt_leadingjet_pt30_eta4p7_vs_pTj2/inputs_JESnuis_pt_leadingjet_pt30_eta4p7_vs_pTj2.py
Labels: enhancement

#48 Combine all Years
  .gitignore
  125.0/hzz4l_2e2muS_8TeV.input.root
  125.0/hzz4l_4eS_8TeV.input.root
  125.0/hzz4l_4muS_8TeV.input.root
  Inputs/Input_Info.py
  Inputs/JES/__init__.py
  RunEverything.py
  efficiencyFactors.py
  python/Utils.py
  python/createXSworkspace.py
  python/interpolate_differential_full3.py
  python/plotAsimov_inclusive.py
  python/plotAsimov_simultaneous.py
  python/plotDifferentialBins.py
  python/plotLHScans.py
  python/producePlots.py
  python/sample_shortnames.py
  runHZZFiducialXS.py
  templates/fiducialXSTemplates.C
  templates/main_fiducialXSTemplates.cpp
Labels: enhancement, urgent

#59 A quick fix for read_jes
  python/read_jes.py
Labels: bugfix
